<a href="https://colab.research.google.com/github/davidest1995/Data-Science/blob/main/Manejo_librer%C3%ADa_numpy_datacodes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Agradar y quitar dimensiones de arrays utilizando las herramientas de la librería numpy.

import numpy as np

vector = np.array([1,2,3])
print(vector)
print(vector.ndim)

expand = np.expand_dims(vector, axis= 0)
print(expand)
print(expand.ndim)

rest = np.squeeze(expand)
print(rest)
print(rest.ndim)

[1 2 3]
1
[[1 2 3]]
2
[1 2 3]
1


In [ ]:
# Creando arrays
import numpy as np
import random 
# lista= (np.arange(0,10,2))
# print(lista)

# np.zeros((10,10))
# np.ones((3,3))
# np.linspace(0,10,10)
# np.eye(4)
# np.random.rand(0,100)
np.random.randint(1,100,(10,10))

array([[78,  9, 15, 75, 60, 98, 31, 87, 94,  3],
       [ 8, 63, 75, 30, 82, 60, 27, 76, 14,  0],
       [23, 83, 70, 97, 77, 18, 77, 73,  0, 99],
       [99, 88, 27, 44, 33, 89, 66, 77, 11, 40],
       [75,  7, 68, 91, 44, 53, 45, 76, 73, 47],
       [ 5, 91, 38, 90, 80,  8, 65, 42, 19, 54],
       [82,  2,  3, 99, 62, 89, 21, 76, 41, 36],
       [84, 22, 35, 22, 19, 83, 93, 87, 38, 33],
       [97, 34, 63, 67, 45, 63,  8, 93, 83, 60],
       [46, 29, 83, 87, 47, 73, 48, 23, 75, 58]])

In [ ]:
import numpy as np

arr= np.random.randint(1,10,(3,2))
print(arr)

print(arr.reshape(1,6))

[[4 6]
 [5 6]
 [1 6]]
[[4 6 5 6 1 6]]


In [ ]:
# Fundiones principales de numpy
from numpy.core.fromnumeric import argmax
import numpy as np

arr= np.random.randint(0,1000,100)
print(f'El arraw inicial es : {arr}')

arr_1= arr.reshape(10,10)

print(f'El array visto como matriz definida previamente: {arr_1}')

num_mayor = arr.max()
num_menor = arr.min()
location_max = arr.argmax()
location_min = arr.argmin()
deltha = arr.ptp()
mediana = np.percentile(arr,50)
desv_est = np.std(arr)
varianza = np.var(arr)
media = np.mean(arr)
arr_2=np.sort(arr)
print(f'El numero mayor del array es: {num_mayor} ,se encuentra en {location_max} y el menor es:  {num_menor}, se encuentra en {location_min}. Su diferencia es: {deltha}')
print(f'La media es: {media}')
print(f'La mediana es : {mediana}')
print(f'La desviación estandar es: {desv_est}')
print(f'La varianza es: {varianza}')
print(f'La matriz ordenada : {arr_2}')

# finalmente puedo concatenar datos, en este caso arr_1 y arr_2

c= np.concatenate((arr_2,arr),axis=0)

print(f'La matriz concatenada es: {c}')



El arraw inicial es : [900 409 140 704 964 588 485 702 859  79 174 612 881 237  31 152 572 794
 782 450 482  86 733 154 198 585 827 544 359 459 310 415 526 243 513 698
 771 240 775  50 944 895 575 734 664 719  23 469 535 447 265 329  59 479
  21  81 955 324 174 697 923 369 464 939 852  56 704 262 280 495  40 592
  76 891 899 972 112 198 774 740 237 454 212 627 391 627 145  38 517 933
 461  26 545 326  24 295  13 773 152 825]
El array visto como matriz definida previamente: [[900 409 140 704 964 588 485 702 859  79]
 [174 612 881 237  31 152 572 794 782 450]
 [482  86 733 154 198 585 827 544 359 459]
 [310 415 526 243 513 698 771 240 775  50]
 [944 895 575 734 664 719  23 469 535 447]
 [265 329  59 479  21  81 955 324 174 697]
 [923 369 464 939 852  56 704 262 280 495]
 [ 40 592  76 891 899 972 112 198 774 740]
 [237 454 212 627 391 627 145  38 517 933]
 [461  26 545 326  24 295  13 773 152 825]]
El numero mayor del array es: 972 ,se encuentra en 75 y el menor es:  13, se encuentra en 9

In [ ]:
# COPY
import numpy as np

arr= np.arange(0,11)
# trozo= arr[0:6] = 100

arr_copy= arr.copy()
arr_copy[2:4] = 12

arr
arr_copy



array([ 0,  1, 12, 12,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Conditions
import numpy as np

arr = np.linspace( 1 , 10 , 10 , dtype = 'int8')
indices_cond = (arr > 4) & (arr < 9)

arr[indices_cond ] = 1

arr

array([ 1,  2,  3,  4,  1,  1,  1,  1,  9, 10], dtype=int8)

In [ ]:
# Operaciones
import numpy as np

# list = [1,2]
# list * 2

arr = np.arange(0,10)
matriz = arr.reshape(2,5)
matriz2 = np.copy(matriz)

matriz @ matriz2.T

# producto_punto = np.matmul(matriz,matriz2.T)
# producto_punto



array([[ 30,  80],
       [ 80, 255]])